export const GLOBALTYPES = {
    AUTH: 'AUTH',
    ALERT: 'ALERT',
    GET_USER: 'GET_USER',
    AUTH_MODAL: 'AUTH_MODAL',
    GET_CATEGORY: 'GET_CATEGORY',
    ADD_CART: 'ADD_CART',
    DELETE_CART: 'DELETE_CART'
}